### ISSUE TITLE
Make it easier to use (+), (-), (==), etc

### ISSUE THREAD

**Issue by Marwes** [gluon-lang/gluon#10]
As no form of overloading currently exist these basic functions require explicit importing like `let { (+), (-), (*) } = prelude.num_Int in 2 + 2`. This is obviously not so nice so some sort of resolution for this problem will be needed. Following is a list of possible ways to resolve this.
- **Implementing overloading with traits/typeclasses/"Ocaml implicit modules"**
  #### Pros
  - Well explored territory
  #### Cons
  - Adds significant complexity to the compiler
- **Use differently named functions for different types (like OCaml)**
  #### Pros
  - No additional complexity added to the compiler
  #### Cons
  - Inconvenient for users
  - Does not solve (==) well as it is often implemented for lots of types. Ocaml has a single (==) operator which takes any any two values as long as they have the same type which works most of the time but then throws errors when comparing functions which is not very friendly.

**Comment by Marwes** [comment]
Initial implmentation of overloading were implemented in ae2264baed146c44f670283295ee88a2e609fe75 and further refined in a few following commits (fea0d4de87915224ee815633bfac17af97e8babe, ff6c930feaff5146b382691df97180efdeb25dd5). 

The short explanation is that when a new variable is created with the same name as an already existing variable an "intersection" is calculated between the types of these two variables. Any further use of this variable then uses the intersected type when inferred.

Example:
```haskell
let f: Int -> Int
in
let f: Float -> Float
// intersect (Int -> Int <=> Float -> Float ===> a -> a)
in {
    x = f 1,
    y = f 1.0,
    // No `f` in scope which takes a `String` so this use will fail 
    z = f ""
}
```
Each of the uses of `f` in the example will then instantiate `f : a -> a` with new variables which will be inferred to `Int -> Int, Float -> Float and String -> String`. After typechecking is complete another pass is then run which renames all overloaded variables to the variable matching their type.

**Comment by Marwes** [comment]
cc #161

**Comment by mikeyhew** [comment]
Can this issue be closed, now that the decision has been made to use implicits?

**Comment by Marwes** [comment]
Yep, thanks for pointing it out!
