### ISSUE TITLE
Consider adding an additional intermediate representation

### ISSUE THREAD

**Issue by Marwes** [gluon-lang/gluon#107]
Currently the AST is the only intermediate representation (IR) and it is directly compiled into bytecode with no extra stage in between. This is mostly fine as the AST has barely any syntax sugar and thus has very little redundancy. However if we are to add additional constructs such as `Getter` as suggested in #103 (`.field` => `\x -> x.field`) or nested patterns in #1 the AST is going to become more and more complex making an additional, simpler IR more valuable as it makes it simpler to implement optimizations and generate code from it.

GHC core is the low level representation I am most familiar with but I am sure there are other alternatives to model it on.
https://ghc.haskell.org/trac/ghc/wiki/Commentary/Compiler/CoreSynType

Something to consider is how this intermediate representation interacts with optimizations such as inlining from a previously loaded module (should the IR be kept so it can be inlined into a module loaded later? If that is the case maybe the IR should be something that could be execute directly?)

**Comment by brendanzab** [comment]
1ML desugars into a minor variation of System Fω. Idiris uses it's own [TT core language](https://github.com/idris-lang/Idris-dev/wiki/Idris-Internals-Guide#coretths).

**Comment by Marwes** [comment]
Closed by #231
