### ISSUE TITLE
Create gluon-lang organisation and transfer repositories

### ISSUE THREAD

**Issue by brendanzab** [gluon-lang/gluon#177]
Now that we have three different repos, it might make sense to start grouping them under an organization.

**Comment by Marwes** [comment]
Actually made the organization last weekend https://github.com/gluon-lang but forgot to bring it up,  wanted to check that there weren't any hidden gotchas but there does not seem to be so I should be able to do this pretty much right away.

**Comment by brendanzab** [comment]
Awesome! Yeah - just need to do a transfer in the repo settings. We might have to switch gitter channels though :(

**Comment by brendanzab** [comment]
Guessing this is done now!
