### ISSUE TITLE
Add universally quantified types

### ISSUE THREAD

**Issue by brendanzab** [gluon-lang/gluon#184]
It would be nice to add universally quantified types to our abstract syntax:

``` rust
pub enum Type<Id, T = ArcType<Id>> {
    ...
    /// Universally quantified type
    Forall(Vec<Generic<Id>>, T),
    ...
}
```

We can figure out concrete syntax later.

**Comment by brendanzab** [comment]
Do we have type schemes in our type checker? This could allow us to simplify that...

**Comment by brendanzab** [comment]
Wondering if this would allow us to do:

```diff
diff --git a/base/src/types.rs b/base/src/types.rs
index a4e08db..bca1eae 100644
--- a/base/src/types.rs
+++ b/base/src/types.rs
@@ -308,24 +308,24 @@ pub enum Type<Id, T = ArcType<Id>> {
     Variants(Vec<(Id, T)>),
     /// Representation for type variables
     Variable(TypeVariable),
-    /// Variant for "generic" variables. These occur in signatures as lowercase identifers `a`, `b`
-    /// etc and are what unbound type variables are eventually made into.
-    Generic(Generic<Id>),
     /// A builtin type
     Builtin(BuiltinType),
     /// A record type
     Record(T),
+    /// Universally quantified type
+    Forall(Vec<(Id, Kind)>,
     /// The empty row
     EmptyRow,
     /// Row extension
     ExtendRow {
         /// The associated types of this record type
-        types: Vec<Field<Id, Alias<Id, T>>>,
+        types: Vec<Field<Id, (T, ArcKind)>>,
         /// The fields of this record type
         fields: Vec<Field<Id, T>>,
         rest: T,
     },
     /// An identifier type. Anything that is not a builtin type.
     Ident(Id),
-    Alias(AliasData<Id, T>),
 }
```

**Comment by brendanzab** [comment]
Seems like `AliasData` is very close to being a universal quantification - it just has an identifier for some reason... 😕

**Comment by brendanzab** [comment]
Here is a useful reference implementation: https://github.com/tomprimozic/type-systems/tree/master/first_class_polymorphism

**Comment by Marwes** [comment]
Its close but not quite the same so I am not sure it is possible to remove args from `AliasData`. Consider `App(Alias("Result", ["a", "b"]), [Int, String])`. `a` and `b` are substituted with `Int` and `String` respectively while for universal quantification they are instantiated with fresh type variables.

**Comment by brendanzab** [comment]
Maybe `Alias` needs a `Kind` associated with it? `App(Alias("Result", Kind::Fun), [Int, String])`?

**Comment by Marwes** [comment]
The kind can be computed from the arguments and a fully applied alias is always `Type` so it would only be necessary for performance reasons.

**Comment by brendanzab** [comment]
What happens if you have:

```
type ResultString = Result String
```

**Comment by brendanzab** [comment]
> Its close but not quite the same so I am not sure it is possible to remove args from `AliasData`. Consider `App(Alias("Result", ["a", "b"]), [Int, String])`. `a` and `b` are substituted with `Int` and `String` respectively while for universal quantification they are instantiated with fresh type variables.

Actually, Wouldn't `Result` be:

```fs
    Result String Int
==> (∀ err val -> | Ok val | Err err) String Int
==> | Ok Int | Err String
```
