### ISSUE TITLE
Correctly handle partially applied types in type bindings

### ISSUE THREAD

**Issue by brendanzab** [gluon-lang/gluon#186]
As discovered in https://github.com/gluon-lang/gluon/issues/184#issuecomment-253978577, we currently don't handle partially applied types in type bindings:

``` fs
type MyResult err val =
  | Ok val
  | Err err

type ResultString = MyResult String

type Foo = Result Int

{ MyResult, ResultString }
```

```
<top>:Line: 1, Column: 1: Kind mismatch
Expected: Type
Found: Type -> Type
type MyResult err val =
^~~~
```

Looks like the kindchecker is inferring the kind of `MyResult` from the number of type arguments in `ResultString`.

**Comment by Marwes** [comment]
Aliases just assume that they have the kind `kind_arg1 -> kind_arg2 -> ... -> Type` but the resulting kind should really be the kind of `AliasData::typ` so I don't think this should be that hard to fix actually.
