### ISSUE TITLE
Just a typo at the crates.io description 

### ISSUE THREAD

**Issue by LifeIsStrange** [gluon-lang/gluon#191]
"A static, type inferred programming langauge for application embedding" 
It's language \* not langauge. 

Thank you for making opensource software.

**Comment by Marwes** [comment]
Thanks! Going to release a patch version fairly soon so we should fix it before that happens. PRs welcome :)

**Comment by LifeIsStrange** [comment]
Sorry I don't know how to do PRs, shame on me :/

**Comment by Marwes** [comment]
Don't worry about it :) (Making a doc change is quite simple though as it can be done solely through the github page, just open the file in question, press the pen/edit button, make the changes and then use the form at the bottom to submit. Will fix it one way or another before the next release however.)

**Comment by brendanzab** [comment]
@LifeIsStrange It's a great time to learn, if you're up for it!

**Comment by LifeIsStrange** [comment]
Well it was very easy, thank you a lot ! :) 
Next step : learning to code ^^
