### ISSUE TITLE
Segfault in the garbage collector in try_gluon

### ISSUE THREAD

**Issue by dgellow** [gluon-lang/gluon#193]
The link to try_gluon server in the readme is dead:
http://ec2-52-29-1-213.eu-central-1.compute.amazonaws.com/

<img width="730" alt="screen shot 2016-10-24 at 02 54 17" src="https://cloud.githubusercontent.com/assets/2451004/19630963/3252d674-9995-11e6-91e0-bc5daac62b5b.png">

**Comment by Marwes** [comment]
Restarted the server. It went down from what looks like a segfault in the garbage collector. Will investigate.
