### ISSUE TITLE
Allow for saving and loading the state of the VM

### ISSUE THREAD

**Issue by lfairy** [gluon-lang/gluon#207]
This feature could be useful for games and such.

See [Eris](https://github.com/fnuecke/eris) and [Pluto](https://github.com/hoelzro/pluto).

**Comment by Marwes** [comment]
Definitely want this, would be neat if this could be implemented via serde so that the serialized format could be customized but since the vm state may contain cycles I am certain if that can work.

Relevant #6

**Comment by Marwes** [comment]
Sketched out a plan for making the sort of stateful serialization/deserialization that this issue needs in serde https://github.com/serde-rs/serde/issues/881. If that sketch turns out to work well this issue should be trivial to resolve afterwards.
