### ISSUE TITLE
Break out the repl into its own crate so that its dependencies aren't required for the gluon crate

### ISSUE THREAD

**Issue by ids1024** [gluon-lang/gluon#267]
Without the `repl` feature, `Cargo.toml` doesn't require `rustyline`, but the repl code is still compiled, and `extern crate rustyline` fails.

**Comment by Marwes** [comment]
Seems I only test [cargo build --lib --no-default-features](https://github.com/gluon-lang/gluon/blob/6f76f9b81fd88d7a73867140a2d3985b9c808238/.travis.yml#L25) ... . Probably need to break out the repl to its own crate.
