### ISSUE TITLE
Let gluon files specify shebang

### ISSUE THREAD

**Issue by Marwes** [gluon-lang/gluon#304]
https://en.wikipedia.org/wiki/Shebang_(Unix)

Basically the parser needs to check if the first line of the file starts with `#!` and if it does, skip that line.

https://github.com/gluon-lang/gluon/blob/793ac60689639e2e8b25d535b96dce5760cffe21/parser/src/lib.rs#L289

**Comment by jgreene** [comment]
Does this need to support any kind of pretty printing like gofmt?  Does gluon have such a formatter?
e.g. When running a pretty printer against the code do we need to retain the shebang line?

**Comment by Marwes** [comment]
> Does this need to support any kind of pretty printing like gofmt?

Good point! The formatter will need to take this into account as well. It is however still in a early stage at the moment so I adding this shouldn't be blocked on the formatter handling it.

That said, adding handling of this to the formatter should boil down to doing the exact same check and if it finds a shebang then prepend the line to the formatted source.

https://github.com/gluon-lang/gluon/blob/91bb687f9a159f8c6fbb2b7c658ad1eeec0b190c/base/src/pretty_print.rs#L263-L273

**Comment by jgreene** [comment]
I've put in a pull request that should resolve this issue # # #312
