### ISSUE TITLE
Add a JSON [de]serializer

### ISSUE THREAD

**Issue by Marwes** [gluon-lang/gluon#333]
Probably needs to be done with a macro which takes a type as an argument (or we let types be passed around as values) which could then be used to leverage serde for serialization.

```f#
type MyType = { x : Int, name : Option String }
let deserializer : String -> Result JsonError MyType =
    json_deserializer! MyType
deserializer "..."
```

Alternatively we could look at how elm's JSON parser works http://package.elm-lang.org/packages/elm-lang/core/5.1.1/Json-Decode though I have hear that it can be difficult to use.

**Comment by brendanzab** [comment]
Personally I've found Elm's json parsers to be quite nice to use!

**Comment by Marwes** [comment]
@brendanzab I think they look quite nice I was only going on what I read somwhere. I guess someone unfamiliar with monads may find them tricky which is perhaps what I got it from.

One downside with elm's approach though is that the serializer and deserializer must be written separately which isn't ideal.

If I were to go for the most pipe-dreamy approach I'd want it to be possible for both approaches to exist and they would be able to call back and forth between eachother. Then it would essentially be possible to use the combinator approach when specialized parsing is required and otherwise lean on the auto generated and fast approach for the bulk of the parsing.

```f#
let special_name_parser : Parser String
/// @derive(Serialize)
type MyType = {
     x : Int,
     /// @serialize(special_name_parser)
     name : String
}
let deserializer : String -> Result JsonError MyType =
    json_deserializer! MyType
deserializer "..."
```

Anyway, getting something simpler up and running should be the first step as the ulterior motive of this issue is that I want to port try_gluon's backend to use the http example in this repo :).
