### ISSUE TITLE
How do I run `io.println("hello world")` from `gluon -i`?

### ISSUE THREAD

**Issue by vi** [gluon-lang/gluon#334]
```gluon
> io.println "hello"
GcPtr(PartialApplicationData { function: Extern(GcPtr(println 0x319e876ab40)), args: ["hello"] })
> :t io.println
String -> IO ()
```

Where is `runIO` or something?

**Comment by Marwes** [comment]
That should just work, sorry. The repl is a bit hard to test so occasionally it breaks in ways like that. Will look into it.

Related #51

**Comment by brendanzab** [comment]
Shouldn't we have something like `:x <expr>` to evaluate expressions in IO? Eg.

```
> :x io.println "hello"
"hello"
```

Perhaps we could have a helpful error if one doesn't use it.

**Comment by brendanzab** [comment]
That's what Idris does at least... it seems in Haskell things 'just work' though:

```
λ ghci
GHCi, version 7.10.2: http://www.haskell.org/ghc/  :? for help
Prelude> print "hi"
"hi"
Prelude> :t print
print :: Show a => a -> IO ()
Prelude>
```

**Comment by Marwes** [comment]
@brendanzab I do like the fact that it just works, maybe it is a bit inconsistent with other monads but there is also nothing else one can actually do with an IO expression than just running it.

The point may become irrelevant with an effect system though
