### ISSUE TITLE
As-patterns

### ISSUE THREAD

**Issue by brendanzab** [gluon-lang/gluon#337]
I've noticed this pattern come up quite a bit:

```ml
let list = import! "std/list.glu"
let { List } = list
```

This could be alleviated if you could (like [in Haskell](https://en.wikibooks.org/wiki/Haskell/Pattern_matching#As-patterns) and [in Rust](https://doc.rust-lang.org/book/second-edition/ch18-03-pattern-syntax.html#-bindings)) give another name binding in patterns:

```ml
let list @ { List } = import! "std/list.glu"
```

**Comment by Marwes** [comment]
Yep, definitely need this. Easy bit of sugar which removes lots of boilerplate given how frequent `let` bindings that unpack are used (since they double as import directives in Haskell, `use` in Rust).

**Comment by Marwes** [comment]
Should also be added to match expressions (can be done separately if it complicates things)

```f#
match x with
| y @ Some _ -> y
| None -> z
```

**Comment by brendanzab** [comment]
Isn't the lhs of a match arm just a pattern? I was thinking we'd add another variant to `ast::Pattern` called `As` or something...

**Comment by Marwes** [comment]
> Isn't the lhs of a match arm just a pattern?

Yep, I guess I should have said it should work with any pattern which an `As` variant would do. Just wanted to document that it should work for patterns in `match` as well as `let` but due to `match` having a more complicated desugar it may not be as easy to get everything working there.
