### ISSUE TITLE
Allow matching on strings and integers

### ISSUE THREAD

**Issue by Marwes** [gluon-lang/gluon#358]
https://gitter.im/gluon-lang/gluon?at=59dec1e2210ac26920d5e686

```f#
match "test" with
| "a" -> 1
| "test" -> 2
| _ -> 3


match 1 with
| 1 -> 11
| 2 -> 22
| _ -> 33
```

**Comment by Marwes** [comment]
Matches like these essentially needs to be compiled into a series of if statements comparing the scrutinee using `==`.

**Comment by zummenix** [comment]
Is #9 related here? I kind of was shocked to know that there is no exhaustive match 😱

**Comment by Marwes** [comment]
I'd say they are mostly separate issues, the only thing exhaustiveness checking needs to do is to just mark these patterns as non-exhaustive unless there is a catch-all binding.

**Comment by zummenix** [comment]
@Marwes I think with some guidance I'll be able to pull it off.
