### ISSUE TITLE
Gluon name

### ISSUE THREAD

**Issue by lloydmeta** [gluon-lang/gluon#361]
Apparently, AWS + Microsoft have come out with their own "Gluon".

https://techcrunch.com/2017/10/12/aws-and-microsoft-double-down-on-deep-learning-with-gluon-a-simplified-ml-model-builder/

Just wanted to bring that to attention. Feel free to close.

**Comment by vyp** [comment]
I don't really see a problem, it just seems like an api specification, not a language or anything. But if that's still an issue, it may actually be worth bringing this up early at https://github.com/gluon-api/gluon-api/, they only have 5 commits at time of writing.

The only issue I can think of here is if someone decides to write a rust gluon-api library, then it might cause confusion, maybe even name conflicts, but gluon-lang is already on crates.io so even then it should mostly be fine I think.

**Comment by Marwes** [comment]
Yep, since the gluon name is taken from something that actually exists https://en.wikipedia.org/wiki/Gluon name collisions such as these are to be expected. As long as the projects are disparate enough that there is little risk for confusion I don't find it to be an issue though.

**Comment by lloydmeta** [comment]
Cool. I'll close this issue then.
