### ISSUE TITLE
ICE when trying to use record field as a type

### ISSUE THREAD

**Issue by vickenty** [gluon-lang/gluon#370]
This program
```
type Foo a = bar.Baz a
{}
```
crashes gluon:
```
thread '<unnamed>' panicked at 'ICE: Alias group were not able to resolve an identifier', /checkout/src/libcore/option.rs:839:4
```

Looks like gluon does not allow specifying types via field access at all. In other situations field as a type produces 'type does not exist' or unification errors, which makes me think that perhaps this syntax should be rejected by the parser?

**Comment by Marwes** [comment]
Yep, looks like I accidentally pushed this commit https://github.com/gluon-lang/gluon/commit/b3aaabdf4661fde1bc03a42f8336a2d8412b602a to master. There is an open issue to add allow projections to work here https://github.com/gluon-lang/gluon/issues/192
