### ISSUE TITLE
Compare the span part in PartialEq for Spanned

### ISSUE THREAD

**Issue by Marwes** [gluon-lang/gluon#394]
From https://github.com/gluon-lang/gluon/pull/393#issuecomment-345504474 

>> it doesn't matter if loc(3) or loc(0) test succeeds anyway. I'm not sure this is intentional.

>That is actually intentional. There are a bunch of parser tests which compares the AST produced by the parser to one that is manually created and I didn't want to spec out the spans for each individual expression in those (since it is relevant for those tests and its quite difficult to mess up the spans so it is not worthwhile to test).

>In hindsight though it would be better to traverse the AST generated by the parser and zero out all spans before doing those comparisons though. Then spans could matter in PartialEq for Span.

Probably a bit of tedious thing to do but should be straightforward.

1. Update [PartialEq](https://github.com/gluon-lang/gluon/blob/22863d39034e8ffd56e929e7a0258f544f3fe1bd/base/src/pos.rs#L261) to compare span

2. Add a `MutVisitor` which overwrites the spans in an entire AST with a dummy span

3. Use the visitor to make sure that the spans are the same as the ones in the manually created ASTs here https://github.com/gluon-lang/gluon/blob/22863d39034e8ffd56e929e7a0258f544f3fe1bd/parser/tests/basic.rs#L711-L745 (may be a few other places as well).

4. (optional) There may be some places where tests fail now where the span was wrong and it should be updated to be correct, rather than using the Visitor to insert a dummy span.

**Comment by zummenix** [comment]
I was looking into implementation of `MutVisitor` and noticed that the signature of `visit_ident` function doesn't allow changing the span since it takes `TypedIdent` not `SpannedIdent`: https://github.com/gluon-lang/gluon/blob/f85090782457e3a488a30faa47c89cf5eb85f3a3/base/src/ast.rs#L344-L346

**Comment by Marwes** [comment]
Ah, I guess the easiest way to remedy that is to add a `visit_spanned_ident` method whose default implementation is to call `visit_ident`. Then update the necessary calls to `visit_ident` to `visit_spanned_ident` where it is necessary (in the `walk_mut_*` functions.

**Comment by zummenix** [comment]
Will it be better if we implement `visit_spanned_ident` as a separate PR?

**Comment by Marwes** [comment]
Nah. That is not necessary. As long as changes are divided up in commits that is enough of a subdivision to make it easy to review.

Besides, having PRs group a number of smaller changes which were ultimately necessary to do a bigger one makes sense to me.
