### ISSUE TITLE
Suggest improvements to the documentation

### ISSUE THREAD

**Issue by Marwes** [gluon-lang/gluon#42]
There is still a lot of parts of gluon which lack documentation and while I will do my best to recognize and improve it where I can, it would be very helpful to get suggestions for which part I should prioritize. Opening a new issue for any needed documentation improvements is often still a good idea but consider this issue a place to add suggestions which do not seem to warrant a separate issue.

**Comment by salpalvv** [comment]
I'd like to recommend generally that the functions and types you use in the tutorial should take priority in documentation. 

I can make specific issues but examples are `Compiler` struct with `new` and `run_expr` methods and `Thread` struct with `get_global` and `define_global` 

Also, adding the bit about importing your own `.glu` files with $GLUON_PATH would be helpful.

**Comment by Marwes** [comment]
Definitely. I actually thought I had documented all functions as core as those already!

> Also, adding the bit about importing your own .glu files with $GLUON_PATH env variable would be helpful.

I am going to refactor the core of the macro expansion code pretty soon so I will add a more thorough explanation of the import macro then as well!

**Comment by salpalvv** [comment]
Yeah, there is a short description for mostly everything. 

One documentation improvement would be to add short examples like [this](https://aturon.github.io/crossbeam-doc/crossbeam/struct.Scope.html)

I'd be happy to take some functions and add [examples + tests](https://doc.rust-lang.org/book/documentation.html) to make the docs more comprehensive. 

I could start with the functions used in the tutorial. I assume most people would gravitate to those first.
