### ISSUE TITLE
How to run gluon after build?

### ISSUE THREAD

**Issue by vishalsodani** [gluon-lang/gluon#427]
Hi,

I downloaded the source code and ran the command `cargo build`. Now, how do I run gluon? I get an error no bin target for the command `cargo run --bin gluon`.

**Comment by Marwes** [comment]
The binary is actually in the `gluon_repl` crate so you need to do `cargo run -p gluon_repl` go run the gluon binary.

I har ut mord there to unclutter the `gluon` crate's dependencies since the real requires  several otherwise irrelevant ones.
