### ISSUE TITLE
How to run gluon programs?

### ISSUE THREAD

**Issue by codec-abc** [gluon-lang/gluon#435]
Hi,

I am a bit puzzled after having read the Readme. I managed to create a rust program to run the sample that print 123 but I was not able to run the bigger sample (the 24 game) because of failing import.

At this point, I am not even sure I took the easiest road to run gluon programs. So, please can you tell me what is the best way to get a setup that make it easy to play around with gluon?

Thanks,

**Comment by Marwes** [comment]
How are you trying to run the sample (`cargo run --example 24`, `gluon examples/24.glu` or using gluon as a library to run it)? What error do you get when running it?

**Comment by codec-abc** [comment]
I am currently using gluon as a library to run it, with [that code](https://gist.github.com/codec-abc/79d03696cf7568f4caed401ab90fd991). [This is the error message](https://gist.github.com/codec-abc/49ddd13fb5b9ca91b12ca68c14005a4e) I print. About the different way of running gluon programs, do you recommend one over others (maybe some are easier to get started)?

**Comment by Marwes** [comment]
Now I see it :). The 24 example requires the `rand` feature to work so you need to enable that in Cargo.toml

```
gluon = { version = ..., features = ["rand"] }
```

Also I recommend you use `fmt::Display` for error printing so they are easier to read.

```
println!("Error during script execution: {}", eval_result.unwrap_err());
```

**Comment by codec-abc** [comment]
Thanks! It might worth adding a note about the rand feature in the readme? (I can do a PR if you want). By the way, is there any other features that need to be enabled in certain cases? 

Thanks for the tip about the `fmt::Display`.

**Comment by Marwes** [comment]
> Thanks! It might worth adding a note about the rand feature in the readme?

At least in `examples/24.glu` there should be a note about it being required but it would not be a bad idea to add a section in the readme about what features exists and what they provide.

> About getting started with gluon, what do you think of publishing release of the REPL (that seems able to run program too) using CI like travis or appveyor?

I had that working before but it broke and I haven't taken the time to look into it (https://github.com/gluon-lang/gluon/releases). I'd quite like to get it working again.

**Comment by Marwes** [comment]
> By the way, is there any other features that need to be enabled in certain cases?

`serialization` is required if you want to store gluon bytecode/values for later consumption. `test` and `nightly` are needed to run tests but that is about it.

**Comment by Marwes** [comment]
Ah, I currently distribute the standard library by compiling the `.glu` files into the library but I have missed to add an entry for `std.random` since it is only conditionally included https://github.com/gluon-lang/gluon/blob/81fd0c485b3bc0d351230627cc996ce75399f91a/src/import.rs#L60-L82 . Thus it only works if `std/random.glu` is in the path when you try to run the program.

It worked for me since I ran it from the root of the repo, if you just want to get it working now you can copy the `std` directory and make sure it can be found from `$PATH` and it should work.

I do need to look into how to better distribute the standard library though.
