### ISSUE TITLE
Improve std.test

### ISSUE THREAD

**Issue by Marwes** [gluon-lang/gluon#471]
- [ ] Allow tests to be named (and these names should be visible when printing)
- [ ] Allow tests to be grouped (and these groups should be visible when printing)
- [ ] Two stage test execution. Tests should first be defined as a data structure see (https://github.com/Marwes/tensile/ or http://haskell.github.io/test-framework/) which then gets executed. This would let us gather information about how many tests there are before starting execution and let it integrate better with tensile
- [ ] Integrate with tensile #468

**Comment by brendanzab** [comment]
Might also be nice to check out these libs for inspiration too:

- https://hspec.github.io/
- https://github.com/elm-community/elm-test

**Comment by Marwes** [comment]
The neat thing about http://haskell.github.io/test-framework/ (and really, any of the Haskell test frameworks) is that they have good interop between various test providers (such as quickcheck etc). The foundation described here should be a fairly solid foundation (it mirrors both hspec and elm-test) and then we can build specialized test on top of this.

I mustn't forget to make tests lazy as `elm-test` has (changing `test : String -> Test a` to ` test: String -> (() -> Test a)`)
