### ISSUE TITLE
Add bit operations on integers and bytes

### ISSUE THREAD

**Issue by Marwes** [gluon-lang/gluon#474]
`>>`, `<<`, `|`, `&`, `^`

They will probably want to have different operator names than the default described above as `<<` and `>>` conflicts with function composition. And `|` conflicts with the `|` in `match` expressions.

**Comment by brendanzab** [comment]
I wonder if just having named functions would be enough here?

**Comment by Marwes** [comment]
This can be done fairly easily by adding these operations as functions at https://github.com/gluon-lang/gluon/blob/b9ec8968b41130a6c7cbb598156ce7e137e95ffc/vm/src/primitives.rs#L351-L374 (for integers, `byte` would need a similar function added to `load_int` and then `load_byte` needs to be added here https://github.com/gluon-lang/gluon/blob/b9ec8968b41130a6c7cbb598156ce7e137e95ffc/src/lib.rs#L597 ).

While this means that these functions will involve Gluon -> Rust function call which is relatively expensive it will work and we can later fix this by special casing on these functions in the byte code generator and generate a plain instruction for them (if the function is fully applied that is). The same strategy could then be used to remove the primitive `#Int+, etc` operators (like in https://github.com/gluon-lang/gluon/pull/204).
