### ISSUE TITLE
Consider using bors to test and merge PRs

### ISSUE THREAD

**Issue by Marwes** [gluon-lang/gluon#487]
[bors](https://bors.tech/) is what https://github.com/rust-lang/rust uses to merge PRs since it makes sure that changes are tested as they will appear on the master branch instead of just testing the the PR branch. 

Since a while back bors appear to be a lot easier to setup for other repos so we may want to consider using it in gluon as well.

### Advantages

* No risk of breaking `master` due to merging subtly conflicting PRs
* Can approve PRs without waiting for the PR testing to conclude (can be useful to approve changes that are minor, Currently I may get pinged about a PR and after reviewing and approving it I still have to come back in 30minutes to merge)

### Disadvantages

* Non-standard way to merge changes on github

**Comment by memoryruins** [comment]
Even though I am fairly new to contributing to repos in general (and thus git/travis/etc too), it only took a moment to adjust enough thanks to the [contributing](https://github.com/gluon-lang/gluon/blob/master/CONTRIBUTING.md) guidelines. Although it isn't a github standard, I imagine it would only take a moment for someone to adjust to, especially if noted in the guidelines.

It appears to work quite well for maintaining rust, and as another advantage, It would be consistent for anyone making PR's to large language projects written in rust.

Most of all, if it gives you more time to focus on features without juggling PRs, it sounds invaluable.

**Comment by Marwes** [comment]
@memoryruins  Thanks for the input! I think I will try and add it fairly soon, if it does not work out it should be simple to remove so no big loss there.
