### ISSUE TITLE
Fail to run 24.glu

### ISSUE THREAD

**Issue by fduxiao** [gluon-lang/gluon#500]
```shell
$ wget https://raw.githubusercontent.com/gluon-lang/gluon/master/examples/24.glu && gluon 24.glu
error: 24:Line: 151, Column: 25: Expected the following types to be equal
Expected: Array Int
Found: Array Char
1 errors were found during unification:
Types do not match:
    Expected: Int
    Found: Char
            if validate digits expr then
                        ^~~~~~

```

gluon version:
```shell
$ gluon --version
gluon 0.7.1
commit: c3316fbe89fea8f1958bc88fd714eb360b9ecc1e
```

P.S. I failed to find how to do type casting when I tried to fix it. 
![panda emoji](http://img.itlun.cn/uploads/allimg/160930/1-160930152340.jpg)

**Comment by Marwes** [comment]
That is definitely a bug in type inference however I haven't been able to reproduce it either on Windows or Linux.

Can you try running the same thing using the gluon from `cargo install gluon_repl --git https://github.com/Marwes/gluon --branch doc` ? I just fixed a bug there that caused compilation to differ between different systems.

**Comment by fduxiao** [comment]
No branch named doc in `https://github.com/Marwes/gluon`. I tried the code on linux getting the same error but with more error logs (too long to paste here). I packed all these for you in a [docker image](https://hub.docker.com/r/fduxiao/gluon/) so you could reproduce it. (I'm trying to push image, but I don't know when it will finish (5KB/s)).
```Dockerfile
FROM base/archlinux
# remove this line if you find the official mirror is fast enough
RUN echo 'Server = http://mirrors.ustc.edu.cn/archlinux/$repo/os/$arch' \
        > /etc/pacman.d/mirrorlist && \
        pacman --noconfirm -Syu base-devel git rust cargo && \
        git clone https://github.com/gluon-lang/gluon /gluon && \
        mkdir /.cargo
# This file specifies crates registry in China. 
# You can just delete the line. 
ADD ./config /.cargo/config
WORKDIR /gluon
# add another mirror
RUN cargo run --release -p gluon_repl examples/24.glu

```

P.S. Thanks to the GFW it took me almost a day to compile but the network was too slow for me even to update the index of crates. So all this things came from the mirrors of [USTC](http://mirrors.ustc.edu.cn/).

**Comment by Marwes** [comment]
> No branch named doc in https://github.com/Marwes/gluon.

Sorry, I merged that branch and deleted (I forgot that I pointed you to it). The fix I mentioned is in gluon-lang/master now though.

Thanks for the docker image, I will try reproducing it with that

**Comment by fduxiao** [comment]
Luckily the uploading is fast. You can now run `docker run fduxiao/gluon` @Marwes .

**Comment by Marwes** [comment]
Pretty sure I got this fixed, thanks for the report!
