### ISSUE TITLE
Change the syntax of attributes/move them out of comments

### ISSUE THREAD

**Issue by Marwes** [gluon-lang/gluon#515]
[Attributes](http://gluon-lang.github.io/gluon/metadata.html) currently reside inside documentation comments which may make it intuitive that they affect the semantics of a program. Making them their own syntactical element could make that clearer.

### Examples

```f#
@implicit
type Monad m = { ... }

@infix left 6
let (+) l r = ...
```

```f#
#[implicit]
type Monad m = { ... }

#[infix(left, 6)]
let (+) l r = ...
```

**Comment by flyingP0tat0** [comment]
I would like to vote in favour of the second example.

**Comment by memoryruins** [comment]
Another option: requiring parentheses in annotations.

```f#,rust,ignore
@implicit
type Monad m = { ... }

@infix(left, 6)
let (+) l r = ...
```

**Comment by Marwes** [comment]
As I don't want to make a release with attributes in comments I am working on adding attributes like `#[implicit]`. I didn't have any real preference so I took the same syntax as rust for convenience.
