### ISSUE TITLE
gluon::vm::api::typ::make_source generates incorrect array type

### ISSUE THREAD

**Issue by Laegluin** [gluon-lang/gluon#542]
`make_source` generates `Array Byte` as type for `vec` of this struct (and mostly likely others, I haven't tested this though). Expected would be `Array Float`.

```rust
struct Struct {
    string: String,
    number: u32,
    vec: Vec<f64>,
}
```

I guess this has to do with `Serializer` implementation, but haven't checked yet.

**Comment by Marwes** [comment]
Seems to be a copy paste error here https://github.com/gluon-lang/gluon/blob/120a91e80d56c5669886a63f6bbb197e674bd13b/vm/src/api/typ.rs#L283 . It should be taking the type from the `SeqDeserializer` (and probably check the `SeqDeserializer` only contains a single type with an assert)
