### ISSUE TITLE
Cannot use constructor when alias of type is in scope

### ISSUE THREAD

**Issue by Laegluin** [gluon-lang/gluon#548]
When defining a type alias for a generic type, like `Option`, that instantiates a type parameter, it is impossible to use the constructor for anything but the type of the alias:

```f#
// works
let something: Option String = Some "something"

type OptionalInt = Option Int

// this is now broken because only `Int` is allowed as type for `Some`
let something: Option String = Some "something"
```

I'm not entirely sure if this is a bug, but it's certainly unexpected, and the error messages are quite confusing,
since you first get an error for the constructor and then for the binding, which seemingly contradict each other.

**Comment by Marwes** [comment]
I believe this is caused by another fix I made in 0.8 to make aliases like this import the constructors of the type they aliases as well (so this brings `Some : Int -> Option Int` into scope, whereas before it didn't do anything).

Only way to fix this might be to make variants scoped under the type (`Option.Some`, `Option.None`). Open for suggestions though.

**Comment by Laegluin** [comment]
> Only way to fix this might be to make variants scoped under the type (Option.Some, Option.None). Open for suggestions though.

Would it be possible to look up the original type that is aliased and import its variants without any type parameters applied? That would import more than you may need, but it wouldn't shadow a more general constructor.

Optionally scoping variants under the type seems useful on its own though, to prevent collisions with identical variants of different types. I'd expect variants qualified like that to work like they do now, so `OptionalInt.Some` would be `Int -> Option Int`, but importing `OptionalInt` would bring `Some : forall a . a -> Option a` into scope as well.

**Comment by Marwes** [comment]
Yep, that seems like a good compromise. I will look into always exporting the variant as the generic type. It is probably just a 1 line change in the typechecker

**Comment by Laegluin** [comment]
> Yep, that seems like a good compromise. I will look into always exporting the variant as the generic type. It is probably just a 1 line change in the typechecker

 Yeah, it doesn't seem like a lot of work, but when I tried yesterday I failed miserably, so I'll better leave this to you :p
