### ISSUE TITLE
Update handlebars to beta4

### ISSUE THREAD

**Issue by sunng87** [gluon-lang/gluon#582]
Hi gluon, first of all thanks for using handlebars-rust in your doc generation. Recently I just updated handlebars 1.0 branch to beta4 with a few performance improvements, and unfortunately, a breaking change in helper API. 

I would like to open a pull request to fix that for you. But the problem is [little-skeptic](https://github.com/Marwes/little-skeptic/blob/master/src/skeptic/Cargo.toml) has handlebars version fixed to beta1, causing conflict:

```
error: failed to select a version for `handlebars`.
    ... required by package `little-skeptic v0.14.0`
    ... which is depended on by `gluon v0.8.1 (file:///home/nsun/tmp/gluon)`
    ... which is depended on by `gluon_codegen v0.8.1 (file:///home/nsun/tmp/gluon/codegen)`
versions that meet the requirements `= 1.0.0-beta.1` are: 1.0.0-beta.1

all possible versions conflict with previously selected packages.

  previously selected package `handlebars v1.0.0-beta.4`
    ... which is depended on by `gluon_doc v0.8.1 (file:///home/nsun/tmp/gluon/doc)`
    ... which is depended on by `gluon_repl v0.8.1 (file:///home/nsun/tmp/gluon/repl)`

failed to select a version for `handlebars` which could resolve this conflict
```

Could you please release a newer version of little-skeptic that removes `=` on handlebars version?

Also if you have any question with handlebars please kindly feedback to me.

**Comment by Marwes** [comment]
Thanks for the heads up and offer to help! I updated little-skeptic and took a look at the breaking changes, as there was only a few, simple errors to fix I just went through and did that immediately as well.

**Comment by sunng87** [comment]
Thanks!
