### ISSUE TITLE
Website down?

### ISSUE THREAD

**Issue by theindigamer** [gluon-lang/gluon#585]
I wanted to read the docs but it seems to be down so I'm reading the source :sweat_smile: .

**Comment by Marwes** [comment]
The server is now up again! Sorry for the trouble! http://gluon-lang.org

**Comment by theindigamer** [comment]
No problem, works for me now :). On an unrelated note, what would you suggest for writing a lexer along with LALRPOP? I was looking at Gluon's code and you seem to have done it entirely by hand, not sure how much of a slowdown it might cause ... I know of [plex](https://github.com/goffrie/plex) but it doesn't really talk about performance and looking at the source there, I can't really tell much. That said, it does seem like it will make my life simpler for now.

**Comment by Marwes** [comment]
I don't mind hand written lexers as they tend to be fairly small, and does not seem to balloon in complexity as much as parsers can. As for runtime performance, I don't know about how fast lexer generators can be but I'd imagine that it is hard to beat an optimized hand written lexer.

(LALRPOP is able to generate a lexer though it is pretty simplistic.)

**Comment by theindigamer** [comment]
> hard to beat an optimized hand written lexer

Well I suppose that might be true but don't you think that it'd be quite hard to work out and maintain all the prefixes correctly? For example, in `token.rs`, you've got:

```
        let token = match ident {
            "and" => Token::And,
            "else" => Token::Else,
            "forall" => Token::Forall,
            "if" => Token::If,
            "in" => Token::In,
            "let" => Token::Let,
            "do" => Token::Do,
            "match" => Token::Match,
            "then" => Token::Then,
            "type" => Token::Type,
            "with" => Token::With,
            src => Token::Identifier(src),
        };
```

I don't know how much `rustc` can optimize these but a generated lexer would not even consider doing all those checks for most identifiers.

Also, the lexer would be able to generate code iterating over `u8`'s in the ideal case, whereas if you're writing it by hand, it would be more work once you include Unicode support.

I guess I'll try out plex :P.

**Comment by chenshuiluke** [comment]
@Marwes hey it seems to be down again. I see that the previous outage was somewhat intentional, but i'm just letting you know in case this one isn't.

**Comment by Marwes** [comment]
Thanks for reporting! Not sure why it went down since it appears that I were deleting the docker logs on every shutdown/crash. That should be fixed now so if it happens again I should be able to tell why.
