### ISSUE TITLE
The implementation of higher-rank types is unsound

### ISSUE THREAD

**Issue by Nadrieril** [gluon-lang/gluon#599]
I was playing around with higher-rank types and discovered that an inner-quantified type could escape, leading to unsoundness:
```
let foo f: forall b. (forall a. a -> b) -> b = f ()
let id x: forall a. a -> a = x
let false: forall a. a = foo id // Oops
let some_int: Int = false
some_int // Undefined behaviour
```
`foo id` should not typecheck, because `forall a. a -> a` and `forall a. a -> b` should not unify.

**Comment by Nadrieril** [comment]
I might be interested in having a look at the typesystem implementation. Is there some documentation/a paper that describes it somewhere ?

**Comment by Marwes** [comment]
I can dig up the papers/implementations I have looked at tomorrow (and I should link these somewhere in the docs as well). I found the issue in subsumption in any case, just have some fallout left to fix.

**Comment by Nadrieril** [comment]
Cool, thanks !
In passing, here is another failure case that makes clearer where the flow of typing fails:
```
let foo f: forall b. (forall a. a -> b) -> b = f ()
let some_int: Int = foo (\a -> if True then a else 42)
some_int
```

**Comment by Marwes** [comment]
The papers on 1ML is a good base for what the type system is supposed to be https://people.mpi-sws.org/~rossberg/1ml/ (at least at a high level).

Implicit arguments are mainly inspired by Ocamls (WIP) implementation https://github.com/ocamllabs/ocaml-modular-implicits and https://www.cl.cam.ac.uk/~jdy22/papers/modular-implicits.pdf (the paper is pretty light on implementation details).

(and more, need to remember which ones though)
