### ISSUE TITLE
Print a hint/warning towards necessary feature gates when importing modules

### ISSUE THREAD

**Issue by Marwes** [gluon-lang/gluon#620]
`regex`, `serialization` and `rand` are features that enable additional modules in gluon but if you forget to enable them then you will get a confusing error message about a missing module. If the error pointed to the feature gate then it would be easier to discover.

The documentation should also be updated to mention the feature gates.

**Comment by Laegluin** [comment]
If you don't mind, I think I should be able to handle that :)

**Comment by Marwes** [comment]
(Another solution is acceptable as well of course :) )

**Comment by Laegluin** [comment]
> (Another solution is acceptable as well of course :) )

haha, I thinks easier to do the `cfg` stuff outside of the functions so you don't have to deal with missing modules (you can actually not compile without serialization because of that right now). I'll play around with it for a bit, we'll see what comes out in the end :)

**Comment by Marwes** [comment]
> you can actually not compile without serialization because of that right now

What do you mean? Everything should still work without the serialization feature, it is only when one tries to use it that an error should occur

**Comment by Laegluin** [comment]
> What do you mean? Everything should still work without the serialization feature, it is only when one tries to use it that an error should occur

Apparently I'm just stupid, I must have accidentally deleted the `cfg` attribute and not noticed :D
