### ISSUE TITLE
Expected/Found type hints seem backwards

### ISSUE THREAD

**Issue by ftilde** [gluon-lang/gluon#627]
Consider the following example
```
let foo _: String -> () = ()
foo 1
```
The resulting error message is:

> error: Expected the following types to be equal
Expected: Int
Found: String
1 errors were found during unification:
Types do not match:
    Expected: Int
    Found: String

Maybe in the context of unification (I don't really know much about that stuff) this makes sense, but from a user's perspective this seems backwards: I supplied (and gluon *found*) an Int, but `foo` *expects* a String.

Also compare the code and the error message to that of a [similar program in rust](https://play.rust-lang.org/?gist=92e04ef16f5f05391eb653cca5b42329&version=stable&mode=debug&edition=2015).

**Comment by Marwes** [comment]
This seems to have regressed while I fixed some cases in subsumption checking. `subsumes` is hard coded to in a way that the more general type is also the expected type whereas that is not always the case. It needs to be able to treat either argument as the expected type.

The error is quite visible at https://github.com/gluon-lang/gluon/blob/bf0a8e48a388c04c556f901f117a22d034d93b6b/check/src/typecheck.rs#L754-L760 where the expected type is passed as the second type argument and not the first, which leads to the correct subsumption check, but the wrong error message.
