### ISSUE TITLE
Accessing non-static data from module loaders

### ISSUE THREAD

**Issue by Laegluin** [gluon-lang/gluon#634]
Since `add_extern_module` takes a function pointer, it's impossible to reference non-static data in a module. Is there a way to do this that doesn't require messing around with global variables? I was looking for a way to simply attach some data to the vm, but I don't think that's possible at the moment.

**Comment by Marwes** [comment]
Tweaked the module loading so that it allows a `Box<FnMut ...>`. Since it's backwards compatible I will pull it into 0.9.1 after I have gone through a few more fixes.
