### ISSUE TITLE
Add implicits similar to rust's io::Read/Write

### ISSUE THREAD

**Issue by Laegluin** [gluon-lang/gluon#653]
I've been playing around with some additions to `std.process`, but I noticed that for working with streams some abstractions are really needed:

- basically rust's io::Read/Write
- Something like `Disposable` for managing resources like file handles

Edit: Just added a rough impl to see if things make sense: https://github.com/Laegluin/gluon/tree/read-write/std

**Comment by Marwes** [comment]
👍 Improving the API around reading and writing to io devices is something I have wanted to improve. Modeling it after `Read` and `Write` in rust seems like a decent start, I haven't looked into what other functional languages do much but I know Haskell has a `Handle` type which acts as an abstract type over any type of IO device (more or less). Don't know how well received that part is though.

http://hackage.haskell.org/package/base-4.12.0.0/docs/System-IO.html#t:Handle

Looked a little bit at the impl, might be a good idea to have the lowest level write function take `Array Byte -> Start -> End` so that sub slices can be written without allocating for the sub slice.

**Comment by Laegluin** [comment]
> Modeling it after Read and Write in rust seems like a decent start, I haven't looked into what other functional languages do much but I know Haskell has a Handle type which acts as an abstract type over any type of IO device (more or less). Don't know how well received that part is though.

I have just skimmed the docs for `Handle`, but to me it seems mix both the IO and the resource part. Overall I think Rust's approach of just having something that writes or reads byte streams is a lot more composable. `Handle` for example seems to also expose whether it's buffered or not, but fundamentally buffering does not change how an IO device works; you can just add it by wrapping it in a type that does the buffering. This also makes custom buffering strategies easier to implement.

Seeking should probably be an additional trait, considering how most of the time, seeking is not actually necessary.

I think the importance of something like `Handle` is mostly resource management. Just having some sort of abstraction for a resource that can be closed should already be really useful. Right now that would not change the usage of course, but I think it's valuable to have because it makes possible language support easier (like `Handle` having some sort of finalizer that is run on gc).

Apart from idioms like Haskell's bracket pattern, one interesting idea is using some specialized binding for resources. I have never used it, but [F#'s `use` binding](https://docs.microsoft.com/en-us/dotnet/fsharp/language-reference/resource-management-the-use-keyword) seems quite nice (not sure how that would work in combination with gluon's monadic IO though).

> Looked a little bit at the impl, might be a good idea to have the lowest level write function take Array Byte -> Start -> End so that sub slices can be written without allocating for the sub slice.

Yep, that's a good idea. Might even make sense to add `type Slice a = { array: Array a, start: Int, end: Int }` to `std.array`.

**Comment by Marwes** [comment]
> I have just skimmed the docs for Handle, but to me it seems mix both the IO and the resource part. Overall I think Rust's approach of just having something that writes or reads byte streams is a lot more composable. Handle for example seems to also expose whether it's buffered or not, but fundamentally buffering does not change how an IO device works; you can just add it by wrapping it in a type that does the buffering. This also makes custom buffering strategies easier to implement.

Yeah, it seems a bit of a catch-all type. It doesn't seem like a good idea to conflate some many things but I figured I should at least bring it up.

**Comment by Marwes** [comment]
> Yep, that's a good idea. Might even make sense to add type Slice a = { array: Array a, start: Int, end: Int } to std.array.

I have thought about slice types quite a bit. Rust handles this so nicely with string and array slices but that isn't exactly an option without a borrow checker :/. I could envision APIs being overloaded on `Array a` and `Slice a` but I can't see that actually working out eronomically :/.

**Comment by Laegluin** [comment]
> I could envision APIs being overloaded on Array a and Slice a but I can't see that actually working out eronomically :/.

Yeah, that seems a bit weird. Maybe arrays could use structural sharing, but that obviously has a whole lot of downsides by itself.

**Comment by brendanzab** [comment]
Might be worth looking at Haskell's Array APIs for inspiration. Still, those could be made nicer with linear or unique types 🤔

**Comment by Marwes** [comment]
Closing this with #655, we can open new issues for any issues and/or improvements that come up!
