### ISSUE TITLE
VmType for BTreeMap seems to be broken

### ISSUE THREAD

**Issue by GTRI-nathan** [gluon-lang/gluon#674]
When trying to do something like `compiler.run_expr::<Vec<BTreeMap<i32,i32>>>(&vm, "example", script)` you get a stacktrace:

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: UndefinedBinding("std.map")', src/libcore/result.rs:999:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:70
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:58
             at src/libstd/panicking.rs:200
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:215
   4: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:478
   5: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:385
   6: rust_begin_unwind
             at src/libstd/panicking.rs:312
   7: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
   8: core::result::unwrap_failed
             at /rustc/ec194646fef1a467073ad74b8b68f6f202cfce97/src/libcore/macros.rs:16
   9: <core::result::Result<T, E>>::unwrap
             at /rustc/ec194646fef1a467073ad74b8b68f6f202cfce97/src/libcore/result.rs:798
  10: <alloc::collections::btree::map::BTreeMap<K, V> as gluon_vm::api::VmType>::make_type
             at ./vm/src/api/mod.rs:1075
  11: <alloc::vec::Vec<T> as gluon_vm::api::VmType>::make_type
             at ./vm/src/api/mod.rs:1011
  12: gluon::Compiler::run_expr
             at ./src/lib.rs:533
  13: marshalling::marshal_wrapper
             at examples/marshalling.rs:333
  14: marshalling::main
             at examples/marshalling.rs:428
  15: std::rt::lang_start::{{closure}}
             at /rustc/ec194646fef1a467073ad74b8b68f6f202cfce97/src/libstd/rt.rs:64
  16: std::panicking::try::do_call
             at src/libstd/rt.rs:49
             at src/libstd/panicking.rs:297
  17: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:92
  18: std::rt::lang_start_internal
             at src/libstd/panicking.rs:276
             at src/libstd/panic.rs:388
             at src/libstd/rt.rs:48
  19: std::rt::lang_start
             at /rustc/ec194646fef1a467073ad74b8b68f6f202cfce97/src/libstd/rt.rs:64
  20: main
  21: __libc_start_main
  22: <unknown>
```

It seems like https://github.com/gluon-lang/gluon/blob/ee1e70555c551f300ede602d358c6bc10acb1fe3/vm/src/api/mod.rs#L1076 isn't finding std.map.Map correctly.

Reproducable by changing https://github.com/gluon-lang/gluon/blob/ee1e70555c551f300ede602d358c6bc10acb1fe3/examples/marshalling.rs#L329 to return the type I mentioned (`compiler.run_expr::<Vec<BTreeMap<i32,i32>>>(&vm, "example", script)`), the script to end with `[]`, and of course add `use std::collections::BTreeMap;` to the top of the file.

Am I missing something I need to do?
(Thanks so much for Gluon, by the way, it's the only Rust-embeddable scripting language I've gotten to compile and run successfully under wasm)

**Comment by Marwes** [comment]
> Am I missing something I need to do?

You actually need to ensure that `std.map` is loaded in the vm before using the `VmType` impl.

```
compiler.load_file(&vm, "std/map.glu")?;
```

This should at least be mentioned on panic message but ideally I think the `VmType` impl should automatically import the necessary module if it is missing. That doesn't quite work however since the `impl` is defined in `gluon_vm` but would need to use things from `gluon`. That might be fixable though, with some refactoring.

**Comment by GTRI-nathan** [comment]
Perfect, thank you so much for your help!
Yeah, running wasm tests seems non-trivial, but if I find anything during development I'll try to help out.

Thanks again!
