### ISSUE TITLE
Add record polymorphism to the Gluon book

### ISSUE THREAD

**Issue by Etherian** [gluon-lang/gluon#675]
You mention that records are capable of polymorphism like rows in the [recent addition](https://gluon-lang.org/doc/crates_io/book/extending-the-guessing-game-with-effects.html#rewriting-io-into-eff) to the book and its [pull request](https://github.com/gluon-lang/gluon/pull/670#issuecomment-450671246). This feature seems really handy, but is not mentioned anywhere in documentation describing records. An explanation of open records could fit well in one of the places records are described in the "Syntax and Semantics" section.

Also, it'd be nice to have something about rows in that section, with all the other primitive types.

**Comment by Marwes** [comment]
Yep, seems I missed adding this (I actually made an issue for it but forgot it again https://github.com/gluon-lang/gluon/issues/366)
