### ISSUE TITLE
Programs that use embedded gluon?

### ISSUE THREAD

**Issue by thrisp** [gluon-lang/gluon#724]
I'm thinking about using this, but I'd like to review more detailed code of programs actually implementing embedded gluon processing. Where can I find some open code to review?

**Comment by Marwes** [comment]
Gluon's repl is implemented in gluon https://github.com/gluon-lang/gluon/tree/master/repl/src and so is https://gluon-lang.org https://github.com/gluon-lang/gluon-lang.org/tree/master/src/app.

I don't maintain a list for other projects (though that could be nice to have in the readme). You may want to ask on https://gitter.im/gluon-lang/gluon if there is someone that has something to share.

**Comment by thrisp** [comment]
thanks
