### ISSUE TITLE
Simple build instructions

### ISSUE THREAD

**Issue by ShalokShalom** [gluon-lang/gluon#726]
Hi there and thanks for this product. Currently, I see zero build instructions overall. How to install just Gluon on my computer, so I can work with it? Cooperating with Rust is a non-goal by now and it seems the current Readme assumes I am a Rust developer and familiar with its package system.

**Comment by Marwes** [comment]
Seems like the README could use an updated there then :) There are binary releases at https://github.com/gluon-lang/gluon/releases which you can use if you don't have/wan't to use cargo

**Comment by ShalokShalom** [comment]
Thanks, I already read it in the Gluon book. Commit is send :+1:

**Comment by ShalokShalom** [comment]
You know that ```cargo install gluon``` wont work? It says ```specified package has no binaries``` here.

**Comment by Marwes** [comment]
Yeah, it isn't the best. `gluon_repl` was a way to avoid a lot of dependencies that aren't used in the main `gluon` library. Might be better to move the binary into the main crate and use feature flags instead.

**Comment by ShalokShalom** [comment]
You could use something like [Habitat](https://habitat.sh/).
