### ISSUE TITLE
Source of the LSP implementation

### ISSUE THREAD

**Issue by ShalokShalom** [gluon-lang/gluon#727]
Currently, I cant find any resource that hints me where the source of the language server protocol implementation is located at. 

I suggest to link it in the Readme, were mentioning it. 

Originally, I looked after it in order to add it to the official implementation overview, while I am doing it for now with the URL of this repo. 

EDIT: Is this the actual LSP implementation, or an own one? 
https://github.com/gluon-lang/gluon_language-server

**Comment by Marwes** [comment]
There are a link in https://github.com/gluon-lang/gluon#language-server maybe you found some other documentation which fails to mention it? Haven't setup a binary release for it so cargo is the only way to install it

**Comment by ShalokShalom** [comment]
It says nowhere that it implements the LSP, specifically. Rust itself implements its own server, so I thought this one may do so as well. If that is LSP conform than you support a lot more editors.

https://langserver.org/

**Comment by Marwes** [comment]
Aha, I misunderstood. When writing "a language server" I just assumed it was clear that it was using the standard protocol. I guess that could use an explicit mention though. The repo also only points out the VS Code support since it also contains the plugin for VS Code which is rather confusing.

**Comment by ShalokShalom** [comment]
So, this is committed now: https://microsoft.github.io/language-server-protocol/implementors/servers/
Thanks!

**Comment by Marwes** [comment]
😆 Figured I shouldn't pollute that list with a tiny language like gluon. Cool to see it on it though, thanks!

**Comment by ShalokShalom** [comment]
Any language once was little. Gluon is little in adoption, not in quality. :hugs:
