### ISSUE TITLE
QML 

### ISSUE THREAD

**Issue by ShalokShalom** [gluon-lang/gluon#731]
Hi there :)

Do to my nearly not existing knowledge and ~~ignorance~~ hope:

Do you see some ways to actually integrate [this](https://github.com/KDE/rust-qt-binding-generator) into Gluon?

There is also an [other](https://github.com/White-Oak/qml-rust) straight forward QML binding to Rust, while pretty old.

**Comment by Marwes** [comment]
It should be possible, but I don't think there is an easy way to just get something working.

Handling mutation (which those bindings appear to use a lot) is something that has improved so that should be fairly doable atm (needs some docs though). What is more problematic is how to figure out and (I assume) generate rust functions which bind to some gluon script. I have some ideas on how to generate bindings purely from parsing and inspecting `.rs` files but haven't done anything for it yet and even when that is added, it might not be general enough to handle this particular case (easily).

**Comment by ShalokShalom** [comment]
And doing it specifically?

**Comment by Marwes** [comment]
> And doing it specifically?

What do you mean?

**Comment by ShalokShalom** [comment]
Do you see the value of QML on a language like Gluon? 
And if so, do you see enough value to implement it specifically?
Opposed to general? Or do you mean your implementation would not be wide enough, feature wise?

**Comment by Marwes** [comment]
> Do you see the value of QML on a language like Gluon?

I have done very little GUI programming (and never with QT) so it is hard for me to say how useful and how well it would work :/ .

> And if so, do you see enough value to implement it specifically?

I don't have any interest in putting work towards integrating with QT specifically. Adding features that work with QT as well as more generally is good though.

> Opposed to general? Or do you mean your implementation would not be wide enough, feature wise?

Well, depending on the "weirdness" of QT specifically, any general solution to generating bindings may not work, or at least not be a complete solution.

When I think about generating bindings I want to first support pure APIs such as say rust's standard library, `regex`, `base64` etc. Building on that, simple mutable state should be added (updating sha digests, mutable collections etc). Beyond that I fear it may be complicated to add a general solution as there is just so many different way any API could be written or used. Specifically GUI libraries tend to have mutable state all over with complicated dependency graphs between components making them hard to write bindings for.

**Comment by ShalokShalom** [comment]
>> I have done very little GUI programming (and never with QT) so it is hard for me to say how useful 
>> and how well it would work :/ .

I mean if you find it valuable to have a GUI toolkit on Gluon.

>> I don't have any interest in putting work towards integrating with QT specifically. Adding features 
>> that work with QT as well as more generally is good though.

OK, fair enough.

>> Beyond that I fear it may be complicated to add a general solution as there is just so many different >> way any API could be written or used. Specifically GUI libraries tend to have mutable state all over >> with complicated dependency graphs between components making them hard to write bindings for.

I guess others can you tell you more. That being said, Qt Widgets is one implementation, Qt Quick is the other one. I am more interested for Qt Quick. This one is suitable for all device types, hardware accelerated and in general the more modern one. I am especially interested because its super easy code: https://doc.qt.io/qt-5/qtqml-syntax-basics.html
