### ISSUE TITLE
Website demo seems broken

### ISSUE THREAD

**Issue by hce** [gluon-lang/gluon#741]
Just tried to run the script found at https://gluon-lang.org/try/ unmodified. Got the following error:

error: error: Could not find module 'std.json.prim'. Searched .
- <std.json.de>:6:20
6 | let prim = import! std.json.prim
  |

**Comment by Marwes** [comment]
Thanks for reporting! Seems I accidentally removed JSON from the allowed modules on there and didn't use the correct vm (with limited modules) when testing the examples. Fixed now.
