### ISSUE TITLE
"Could not find type 'my.module.MyEnum'" when defining a gluon type in rust

### ISSUE THREAD

**Issue by hce** [gluon-lang/gluon#743]
I'm trying to export an enum to gluon like this:

    #[derive(Debug, Getable, Pushable, VmType)]
    #[gluon(vm_type = "my.module.MyEnum")]
    pub enum MyEnum {
        Hello, World, Experiment
    }

When using a vm.get like this:

    let mut callback_function: Option<FunctionRef<fn(String, Vec<String>, Vec<MyEnum>) -> (Vec<String>)>> = None;
    [...]
    if let Ok(s) = vm.get_global("user.callback_Function") {
        eprintln!("ok!");
        callback_function = Some(s);
    }

I'm getting the following error:

    thread 'main' panicked at 'Could not find type 'my.module.MyEnum'. Is the module defining the type loaded?', src/source.rs:73:36

I've tried to declare the type using Thread::register_Type but to no avail.

What am I missing?

**Comment by Marwes** [comment]
You should only need to use  `#[gluon(vm_type = "my.module.MyEnum")]` if you need to refer to a type defined elsewhere. In this case you should be fine just omitting that attribute.

`register_type` is mainly used to create an opaque type which you can refer to later which I don't believe is what you want here as you (presumably) want to refer to the variants of the enum from gluon.

**Comment by hce** [comment]
Ok, great, that does seem to work.

How can I match the enum with "match", though? It seems the field names are not exported to gluon.

**Comment by Marwes** [comment]
The `record!` macro also accepts types which will be exported and be accessible on the gluon side https://github.com/gluon-lang/gluon/blob/45427d5d1b7cde9ca4160a2b2d672bf4a6003a68/src/std_lib/http.rs#L385-L399

**Comment by hce** [comment]
That works, thanks a lot! :-)

**Comment by hce** [comment]
I think this can be closed now, thanks again. I'll probably submit a pull request with some documentation on this at some point.

One last question: This vm_type attribute is only needed to implement the standard library, correct? Because it seems using this allows gluon code to cause a panic on the rust side, which isn't something desirable.

**Comment by Marwes** [comment]
https://github.com/gluon-lang/gluon/blob/45427d5d1b7cde9ca4160a2b2d672bf4a6003a68/repl/src/repl.rs#L193-L203

It is mainly used to define opaque types which are also useful outside of the standard library. It isn't exactly easy to use properly though since the type needs to be registered before referring to the type.
