### ISSUE TITLE
Pattern matching error on type aliases

### ISSUE THREAD

**Issue by colinbankier** [gluon-lang/gluon#749]
First of all, thanks for the amazing work on Gluon - I've just starting playing with it, and I'm pretty excited about its potential.

I found an unexpected case where pattern matching doesn't work if the type is a type alias.
e.g.
```
type MyType = (String, Int)

let getName thing : MyType -> String =
    let (name, count) = thing
    name
```
This compiles fine (according to the language server anyway), but fails when run with "Undefined variable `name`".
If, however the function is defined as
```
let getName thing : (String, Int) -> String =
    let (name, count) = thing
    name
```
it works. I would expect these to be equivalent.
Gluon version 0.11.2

**Comment by Marwes** [comment]
Thanks for the report! Fixed with #750
