### ISSUE TITLE
`split_at` panics on index out of bounds

### ISSUE THREAD

**Issue by lePerdu** [gluon-lang/gluon#757]
Example:
```
> let { split_at } = import! std.string
> split_at "abc" 4
thread '<unnamed>' panicked at 'byte index 4 is out of bounds of `abc`', src/libcore/str/mod.rs:2010:9
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Canceled', src/libcore/result.rs:997:5
```

Other string functions (`char_at` and `slice`) and array functions (`index`) don't crash the rust thread on invalid input, but they still "panic" the vm. Is there a reason these (and other) functions don't return `Option`s?

**Comment by Marwes** [comment]
Looks like an omission, they should "panic the vm" just like the array functions but currently they just use the raw rust functions.
