### ISSUE TITLE
Can't export Userdata value from module

### ISSUE THREAD

**Issue by lePerdu** [gluon-lang/gluon#761]
## Use Case
I've playing around with using gluon in a text editor. It's using [`xi_rope::Rope`](https://docs.rs/xi-rope/0.3.0/xi_rope/rope/type.Rope.html) to store text, which is marshalled to gluon as `Userdata` (in a new-type wrapper). This works fine, but when I tried to implement `Monoid` for it, gluon gave a runtime error saying "Userdata cannot be cloned" when importing the module, because of the `empty` field of `Monoid`. The same error occurs when exporting a Userdata literal from an `ExternModule`. I have a stripped-down example below:

## Minimal example
```rust
#[derive(VmType, Trace, Userdata, Clone, Debug)]
#[gluon_trace(skip)]
#[gluon(vm_type = "mystring.MyString")]
struct MyString(String);

fn load_mystring(vm: &Thread) -> VmResult<ExternModule> {
    vm.register_type::<MyString>("mystring.MyString", &[])?;

    ExternModule::new(vm, record! {
        from_str => primitive!(
            1, "mystring.from_str", |s| MyString(s)),
        // This causes an error
        empty => MyString(String::new()),
    })
}

fn main() {
    let vm = gluon::new_vm();
    add_extern_module(&vm, "mystring", load_mystring);

    let mut compiler = Compiler::new();
    // Import to module to bring in the MyString type
    match compiler.run_expr::<OpaqueValue<&Thread, Hole>>(
        &vm, "", "import! mystring")
    {
        Ok(_) => {}
        Err(e) => { panic!("{}", e); }
    };

    match compiler.run_expr::<UserdataValue<MyString>>(
        &vm, "", r#"
            let mystring = import! mystring
            mystring.empty
            // This works fine: mystring.from_str "abc"
        "#)
    {
        Ok((result, _)) => { println!("{:?}", result); }
        Err(e) => { panic!("{}", e); }
    };
}
```

Error:
```
thread 'main' panicked at 'error: Userdata cannot be cloned
- <>:1:9
  |
1 | import! mystring
  |         ^^^^^^^^
  |
', src/main.rs:48:21
```

Commenting out the `empty` export and returning the expression `mystring.from_str "abc"` works fine.

**Comment by Marwes** [comment]
```rust
empty => MyString(String::new()),
```

Ends up storing an actual `MyString` in the module which ends up needing to be cloned during module loading. It is possible to enable userdata to be cloned by implementing https://docs.rs/gluon_vm/0.12.0/gluon_vm/api/trait.Userdata.html explicitly instead of deriving but it isn't as easy as it should be. 

```rust
fn deep_clone(
    &self,
    deep_cloner: &mut Cloner
) -> Result<GcPtr<Box<dyn Userdata>>> {
        deep_cloner.gc().alloc(Move(self.clone()))
}
```

It should really be a simple attribute on the derive macro to enable though (`#[gluon_userdata(clone)]`).

An easier workaround would be to expose empty as a function `empty => primitive!(1, "module.empty", |()| MyString(String::new())),`

**Comment by lePerdu** [comment]
I tried that workaround before, but the same error occurs when I try to make and export the `Monoid` instance in gluon since `Monoid.empty` is a still value, not a function.

**Comment by lePerdu** [comment]
Also: `Cloner` doesn't seem to be exported (unless I'm missing something). Is it supposed to be, or is there a way to manually implement `Userdata` without referencing that type?

**Comment by lePerdu** [comment]
After exporting `Cloner`, the code you gave worked (after wrapping the value in a Box and helping the typechecker). I put in a PR with the attribute you mentioned.
