### ISSUE TITLE
Marshalling recursive datatypes

### ISSUE THREAD

**Issue by lePerdu** [gluon-lang/gluon#765]
Is it possible to marshal recursive datatypes (e.g. `List`) back and forth between gluon and rust directly? The LISP example uses opaque types and functions which extract data from them to accomplish this, but I was wondering if it is / will be possible to, for example, write this type in rust:
```rust
enum List<T> {
    Nil,
    Cons(T, Box<List<T>>),
}
```
and then pass it directly to gluon (my attempts at implementing `VmType` for this wouldn't unify and the `derive` implementation overflows the stack).

**Comment by Marwes** [comment]
Added an example in #768 . It is possible but specifically `VmType` can't be derived directly for recursive values. It is ok to point it to a type defined in gluon though (given that the types are compatible).
