### ISSUE TITLE
0.12.0 doesn't compile out of the box

### ISSUE THREAD

**Issue by OWilliam** [gluon-lang/gluon#792]
I added a gluon = 0.12.0 dependency to a new project but got:
error[E0277]: `syn::NestedMeta` doesn't implement `std::fmt::Debug`
  --> /usr/local/google/home/willosborn/.cargo/registry/src/github.com-1ecc6299db9ec823/gluon_codegen-0.12.0/src/attr.rs:72:79
   |
72 |                     _ => panic!("unexpected gluon container attribute: {:?}", meta_item),
   |                                                                               ^^^^^^^^^ `syn::NestedMeta` cannot be formatted using `{:?}` because it doesn't implement `std::fmt::Debug`
   |
   = help: the trait `std::fmt::Debug` is not implemented for `syn::NestedMeta`
   = note: required by `std::fmt::Debug::fmt`

Looks like you need to change this line:
https://github.com/gluon-lang/gluon/blob/3a5ef581270d94d5a105139d93cf8b1cf266343a/codegen/src/attr.rs#L80
or add the extra-traits feature to the syn dependency in your Cargo.toml.

**Comment by Marwes** [comment]
Sorry, about that. Since there is a work around by adding the necessary features manually I will just roll forward by releasing 0.13 next week.

**Comment by OWilliam** [comment]
Thanks for your prompt reply and your great work on gluon.

**Comment by Marwes** [comment]
0.13 is out on crates.io but it has a deadlock when running on multiple (native) threads. Working on a fix but if you don't use gluon from multiple threads it should be ok.

**Comment by Marwes** [comment]
0.13.1 is now out as well with the deadlock fix.
