### ISSUE TITLE
Deadlocking on function deserialization

### ISSUE THREAD

**Issue by omegablitz** [gluon-lang/gluon#805]
Gluon seems to deadlock when deserializing serialized values in some circumstances.

Minimal reproduction: https://github.com/omegablitz/gluon-bug

**Comment by Marwes** [comment]
Fixed (accidentally) in https://github.com/gluon-lang/gluon/pull/803 . Making a fix on master requires more of a workaround (without just doing the more involved fix that ended up in #803 ).

For now, you can ensure that all modules that you use are loaded in the new vm before you try to deserialize the value
