### ISSUE TITLE
GetOffset crash on pattern match

### ISSUE THREAD

**Issue by omegablitz** [gluon-lang/gluon#807]
The following code crashes with a `GetOffset on 5` error:
```
let option @ { ? } = import! std.option

let crash opt =
    match opt with
    | None -> 0
    | Some -> option.unwrap opt

crash (Some 5)
```
(I realize that I should be unpacking instead of using `option.unwrap`, but this is the smallest reproduction I could find)

I haven't looked in detail into where this error originates, but I suspect it's because it's being matched into `Some` instead of `Some _`. If this is the case, the error should be caught at typecheck time.

**Comment by Marwes** [comment]
Thanks for the report! The typechecker only checked that there weren't to many argument specified.
