### ISSUE TITLE
Unclear how to refer to Userdata

### ISSUE THREAD

**Issue by huin** [gluon-lang/gluon#811]
In this Gist: https://gist.github.com/huin/e89ec0b11d6c5906ade3fde735ba2ade it's not clear how to refer to the `MyUserdata` type from within Gluon. I've not found any documentation on how to do this, so it might just be missing documentation.

It *feels* like the return value from `register_type` ought to be fed back into the `ExternalModule`, but `ArcType` does not implement `Pushable`.

**Comment by Marwes** [comment]
Yes, this example should be updated to show how to refer to external types https://github.com/gluon-lang/gluon/blob/4a59d18d263d40a35a50c3685f0ea37d5e57de86/examples/marshalling.rs#L332-L398 .

They can be exported like in https://github.com/gluon-lang/gluon/blob/4a59d18d263d40a35a50c3685f0ea37d5e57de86/vm/src/primitives.rs#L595-L621 . So something like this should work https://gist.github.com/Marwes/f9924b50173546208770517c7e378827

**Comment by huin** [comment]
Thanks for the quick response and updated docs! Confirmed that your advice has worked.
