### ISSUE TITLE
How to use Thread::run_expr_async()?

### ISSUE THREAD

**Issue by ababo** [gluon-lang/gluon#820]
It seems like your documentation doesn't cover `Thread::run_expr_async()`. I try to call the VM asynchronously within `tokio` event loop not to block it and get an abscure compilation error:

```rust
use gluon::{self, ThreadExt};

/// An executor error.
pub enum Error {
    GluonError(gluon::Error),
}

/// A command executor.
pub struct Executor {
    thread: gluon::RootedThread,
}

impl Executor {
    /// Creates a new Executor instance.
    pub fn new() -> Executor {
        let mut thread = gluon::Thread::new();
        thread.run_io(true);
        Executor { thread: thread }
    }

    /// Executes a given Gluon script.
    pub async fn execute(&mut self, script: &str) -> Result<(), Error> {
        let res = self.thread.run_expr_async::<()>("test", &script).await;
        match res {
            Ok(()) => Ok(()),
            Err(err) => Err(Error::GluonError(err)),
        }
    }
}

```
```
error[E0277]: the trait bound `dyn futures::future::Future<Item = ((), gluon_base::types::ArcType), Error = gluon::Error> + std::marker::Send: std::marker::Unpin` is not satisfied
  --> crawler/src/executor/mod.rs:23:19
   |
23 |         let res = self.thread.run_expr_async::<()>("test", &script).await;
   |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `std::marker::Unpin` is not implemented for `dyn futures::future::Future<Item = ((), gluon_base::types::ArcType), Error = gluon::Error> + std::marker::Send`
   |
   = note: required because of the requirements on the impl of `std::future::Future` for `std::boxed::Box<dyn futures::future::Future<Item = ((), gluon_base::types::ArcType), Error = gluon::Error> + std::marker::Send>`
```
I suspect I don't get the semantics of this call. Can you explain where I am wrong here? We definitely need some documentaion covering this, especially now, when `async/await` has been stabilized.

**UPDATE** Actually I need the VM to call my `async` functions written in Rust. I.e. it's not a problem that pure in-VM execution will block the event loop, but I need Gluon to unblock it when calling my `async` functions.

**Comment by Marwes** [comment]
The version on crates.io use futures-0.1 so you need to use https://docs.rs/futures/0.3.4/futures/compat/trait.Future01CompatExt.html#method.compat to convert it into a std::futures::Future. The version on git is updated to std::futures::Future/tokio-0.2

**Comment by ababo** [comment]
Hmm, don't you have an example of using that somewhere in Gluon documentation?
