### ISSUE TITLE
multiline input in REPL

### ISSUE THREAD

**Issue by codesections** [gluon-lang/gluon#830]
Thanks very much for your work on Gluon.  I just started trying it out, but it already seems very impressive.

However, in my first few minutes playing with Gluon I've run into a basic issue.  (It could well be user error and, if so, I apologize.  But I didn't see anything in the Gluon Book or github issues that seemed to address this).  

The issue I'm running into is that I cannot enter multiline forms in the REPL.  For example, I attemtempted to type in the Fibinacci example: 

```gluon
let fib n =
  if n #Int< 2
  then 1
  else fib (n #Int- 1) #Int+ fib (n #Int- 2)
fib
```

Unfortunately, pressing `Return` at the end of the first line does not open a block; it provides the error `error: Unexpected token: CloseBlock` instead.  I tried common key combinations, (`Shift + Return`, `C-j`, `C-Return`, etc.) but none of them opened a block either.

Am I missing something obvious here, or does the REPL not support multiline input?

**Comment by Marwes** [comment]
No, the REPL just doesn't support multiline input yet. Unsure exactly how to determine when multi line is expected vs just returning a parse error

**Comment by codesections** [comment]
Thanks for the quick reply.  It's a bit disappointing to learn that the REPL doesn't allow multi-line input, but reassuring to know I  wasn't missing something obvious.

> Unsure exactly how to determine when multi line is expected vs just returning a parse error

I haven't looked at the code, but here's one approach: Any time the REPL encounters an unexpected `CloseBlock` token on a non-empty line, it should replace the `CloseBlock` with a newline + indentation.  (This would mean that some invalid input wouldn't trigger parse errors immediately, but that seems to be an acceptable trade off – it's the same trade off shells typically make with open blocks (e.g., an open quotation mark in bash).)
