### ISSUE TITLE
Website not accessible

### ISSUE THREAD

**Issue by wezm** [gluon-lang/gluon#840]
Hi, just tried to read the docs but the website seems to be down:

```
$ curl -I http://gluon-lang.org/book/index.html
curl: (7) Failed to connect to gluon-lang.org port 80: Connection refused
```

**Comment by Marwes** [comment]
Fixed now, I were making some changes to its build process which broke it for a while.

**Comment by RussianCow** [comment]
@Marwes It appears to be down again (still?).

**Comment by wezm** [comment]
@RussianCow seems to be working now.

**Comment by RussianCow** [comment]
@wezm Thanks for chiming in. Weirdly, it doesn't work on my desktop at all, but works on every other device I have, so I'm chalking it up to a weird DNS issue or similar. Hopefully it resolves itself.
