### ISSUE TITLE
Passing BTreeMap from rust function to Gluon script results in panic

### ISSUE THREAD

**Issue by ikaeon** [gluon-lang/gluon#847]
Test program can be found here: https://github.com/ikaeon/gluon_btreemap
with the output of 
RUST_BACKTRACE=full  cargo run asx.glu &> stacttrace.txt
found in the misspelt  stacttrace.txt

The panic message is:
thread 'main' panicked at 'Attempted to pop Frame { offset: 0, state: Unknown, excess: false } but btreemap was expected', /home/me/.cargo/registry/src/github.com-1ecc6299db9ec823/gluon_vm-0.15.1/src/thread.rs:1936:13

but it changes depending on the number of items in the BTreeMap

**Comment by Marwes** [comment]
I can't reproduce this from the repo :(

**Comment by ikaeon** [comment]
Let me update my system(Archlinux) and I will get back to you.

**Comment by ikaeon** [comment]
I had modified the code by commenting out some lines in main.rs for some other testing and unintentionally push the change.
I current repo has up to date code that fails both
cargo run asx.glu
cargo run test.glu
