### ISSUE TITLE
Make the VM's value printing take the type into account

### ISSUE THREAD

**Issue by Marwes** [gluon-lang/gluon#85]
The current value printer does not take the type of the value into account as a raw `Value` is not aware of its actual type. This leads to some compromises in the information the printing displays. Adding a second way of printing which is aware of the type would be nice so that the REPL top level can print better values

``` rust
pub struct TypedValue<'a>(&'a TcType, Value);
impl<'a> fmt::Display for TypedValue<'a> { ... }
```

[remove_aliases_cow](https://github.com/Marwes/gluon/blob/8919350e13c950304826968fc8789c8d81b91044/base/src/instantiate.rs#L33) can be used to see the actual type of the value (variant (| None | Some Option a), record { x : Int, ... } or a primitive (Int, Float, ...))

**Comment by Marwes** [comment]
Related #83

**Comment by Marwes** [comment]
Would like to have this for https://github.com/gluon-lang/gluon_language-server/pull/4 but maybe the current printing is adequate for the initial debugger support. Unless @brendanzab you would like to implement it?

**Comment by brendanzab** [comment]
Not going to have a chance to look at this right now... sorry!

**Comment by Marwes** [comment]
No worries, just wanted to suggest it as an easier issue than universal quantification if you get stuck to much on that :)
