### ISSUE TITLE
Simple way to construct Map values in Gluon?

### ISSUE THREAD

**Issue by crides** [gluon-lang/gluon#876]
In Gluon, the `{ ... }` syntax is used for records, which are Rust/C like structs, but there's no easy way to construct `std.map.Map` values, so that the result is dynamic. Since there's no method to directly convert a record to a Map in either Rust or Gluon, is it possible to actually do this as a library user? I would imagine it would require tapping into the compiler to get the field names for the record and the values from the record itself.

**Comment by Marwes** [comment]
An issue of converting records into maps is that the map requires that all values have the same type. So it isn't obvious what `{ int: Int, string: String }` should be converted to `Map String ?`.

What may work for you is to serialize the record into a json value https://gluon-lang.org/doc/crates_io/std/std/json/ser.html#value.serialize however that won't work for arbitrary records, you need to implement `Serialize` on each record type to use (which can be done easily by deriving at least).
