### ISSUE TITLE
IO monad debug behavior

### ISSUE THREAD

**Issue by rustrust** [gluon-lang/gluon#884]
I am new to gluon (and fp). i run the following gluon script using the latest (https://github.com/gluon-lang/gluon/commit/0c26ceefc3bdf7890dec59227d5f974e3632133a) and all that prints is "the spoon is too big" although i have set --debug high.

Maybe for whatever reason this is a desirable behavior, but I find this quite confusing. Would it be possible to have some documentation on the right way to compose these io calls and maybe some kind of warning or newbie mode?

```
let io = import! std.io

io.println "Hello world!"
io.println "i am a banana"
io.println "the spoon is too big"
```

**Comment by Shuenhoy** [comment]
You didn't compose them, you just created three irrelevant `IO ()`, and only the last `IO ()` is returned from this module.

You can try this, chain them with bind operator:

```gluon
let io @ {?} = import! std.io
let {(>>=)} = import! std.monad

io.println "Hello world!" >>= (\_->
    io.println "i am a banana" >>= (\_->
        io.println "the spoon is too big"
        )
    )
```


Or with equivalent do-notation(something like syntax sugar of bind operator)：
```gluon
let io @ {?} = import! std.io

seq io.println "Hello world!" 
seq io.println "i am a banana"
io.println "the spoon is too big"
```

**Comment by Marwes** [comment]
The ability to write multiple statements like that should really just be removed, I just keep forgetting it is still in there.

(Forbid

```

io.println "Hello world!"
io.println "i am a banana"
```
)

**Comment by Etherian** [comment]
Forbidding consecutive statements would also allow for nice error messages that could help teach users how to compose IO actions.

**Comment by rustrust** [comment]
Cool. I personally prefer Etherian's error message approach to this but automatically ```seq```-ing the IO actions is fine too.
