### ISSUE TITLE
Using variables from surrounding scope in macro expansion

### ISSUE THREAD

**Issue by bch29** [gluon-lang/gluon#895]
I am trying to write a `format!` macro as a type implementing the `Macro` trait. I would like to be able to invoke it like this

```gluon
let x = 1
let y = 2
format! "x'={1+x}, y={y}"
```

where the above would expand to

```gluon
let x = 1
let y = 2
"x'=" ++ show (1 + x) ++ ", y=" ++ show y
```

I have written the code to produce this expansion, but when I try to use it I get errors telling me that `(++)`, `show`, `x` and `y` are undefined. I have tried using `let symbols = Symbols::new();` and

```rust
let mut compiler_db = env.vm.get_database();
let mut compiler = env.vm.module_compiler(&mut compiler_db);
let symbols = compiler.mut_symbols();
```

for symbol lookup (passed to `parse_expr` to parse subexpressions, and for getting the `show` and `(++)` identifiers).

I could make this work by having the user pass symbols in like this

```gluon
let fmt = { show, (++) }
let x = 1
let y = 2
format! fmt "x'={x'}, y={y}" {x' = 1+x, y}
```

where the last line would expand to something like

```gluon
let args = {x' = 1 + x, y}
in "x'=" ++ fmt.show args.'x ++ ", y=" ++ fmt.show args.y
```

but I believe this is less pleasant to use. Is it possible to achieve my desired syntax with a macro?

**Comment by Marwes** [comment]
I think if you create the symbols on the `Symbols` map passed in to expand after https://github.com/gluon-lang/gluon/pull/896 it should work as you expect.

**Comment by bch29** [comment]
Thanks for the fast response to this! I have tried that branch and still can't quite get it to work. Passing that symbols map to `parse_expr` lets it pick up locals from subexpressions correctly, but I am still getting errors on `show` and `(++)`. Am I doing something wrong by creating a show expression like this?

```
ast::Expr::Ident(ast::TypedIdent::new(symbols.from_str("show")))
```

**Comment by bch29** [comment]
I have opened a PR including my `format!` implementation at #897 since you have an open issue to add such a macro.

**Comment by Marwes** [comment]
I don't think you should rely on `show` and `++` to be in scope for the macro. Instead expand it to be `let { show } = import! std.show in let { (++) } = import! std.string in ...`

**Comment by bch29** [comment]
I wasn't sure if it was possible to put macro invocations in the AST, so I have had it look up the import macro in the `MacroEnv` then expanded it. This works nicely.

**Comment by Marwes** [comment]
Ah, right. The expansion should work iteratively on the output of an expansion as well.
