### ISSUE TITLE
error E0603

### ISSUE THREAD

**Issue by Zuzuk-null** [gluon-lang/gluon#904]
When i use `cargo install gluon_repl` or `cargo install gluon_language-server`, rustc reports an error E0603

   Compiling serde_state v0.4.7
error[E0603]: module `private` is private
   --> /home/daniil/.cargo/registry/src/github.com-1ecc6299db9ec823/serde_state-0.4.7/src/private/de.rs:16:16
    |
16  | pub use serde::private::de::InPlaceSeed;
    |                ^^^^^^^ private module
    |

**Comment by imjdl** [comment]
I encountered the same problem.

**Comment by Marwes** [comment]
Uploaded a fixed version of `serde_state` so this is fixed
