### ISSUE TITLE
`const _: [(); 8 * 6] = [(); std::mem::size_of::<Type<Symbol, ArcType>>()];`

### ISSUE THREAD

**Issue by llogiq** [gluon-lang/gluon#912]
I get `expected an array with a fixed size of 48 elements, found one with 40 elements`. It may be that something changed with the current Rust, but I cannot compile gluon.

```
$ rustc -vV
rustc 1.52.0 (88f19c6da 2021-05-03)
binary: rustc
commit-hash: 88f19c6dab716c6281af7602e30f413e809c5974
commit-date: 2021-05-03
host: x86_64-unknown-linux-gnu
release: 1.52.0
LLVM version: 12.0.0
```

**Comment by Marwes** [comment]
Fixed by https://github.com/gluon-lang/gluon/commit/4bd920bf00ffffc22f7a2c68b171110145512bc5
