### ISSUE TITLE
Is gluon-salsa still active?

### ISSUE THREAD

**Issue by cnehren-tenable** [gluon-lang/gluon#919]
I'm looking at using gluon-salsa for an internal project. It has asynchronous query support, something very important for my work projects. I'm not able to find a source repo for the project and the crate was uploaded more than a year ago. Should I be looking elsewhere?

**Comment by Marwes** [comment]
It is only meant as an internal package for gluon itself so don't expect any updates to it, Ideally https://github.com/salsa-rs/salsa/pull/244 (and https://github.com/salsa-rs/salsa/pull/245 ) would be merged upstream which would make `gluon-salsa` obsolete.

The source exists in a branch here https://github.com/Marwes/salsa/tree/gluon_salsa

**Comment by cnehren-tenable** [comment]
I understand that it's only an internal package; that's part of our evaluation. We've looked at those bugs, too, but it appears that they're waiting for Niko to review. I understand that folks have other things going on and that's fine, so we're considering looking at this fork in the meantime. Thank you for all the helpful information! This'll help a great deal with our decisions. :)
