### ISSUE TITLE
Release a new version?

### ISSUE THREAD

**Issue by eduardosm** [gluon-lang/gluon#947]
Can we have a new version released to crates.io?

Otherwise, `cargo install gluon_repl` is broken due to https://github.com/gluon-lang/gluon/issues/938.

**Comment by slyons** [comment]
Seconding this

**Comment by MarkuBu** [comment]
Latest Release is from 2020?

**Comment by Marwes** [comment]
Latest release is 6 month old (0.18.2), I think I never migrated the travis CI release bits to github actions so new releases (of which there aren't really any) won't be uploaded to github.

**Comment by Marwes** [comment]
If the release to crates.io is broken again, please re-open this issue
