### ISSUE TITLE
Report a vulnerability in gluon-lang/gluon

### ISSUE THREAD

**Issue by snowroll** [gluon-lang/gluon#956]
Hello, we have found a vulnerability in this repository, which may present serious security risks. However, we have been unable to locate a contact email to report the details of this vulnerability. We would like to know if you can provide an email address to confidentially discuss this matter and avoid public disclosure.

**Comment by Marwes** [comment]
My email should be visible on my profile so you could send it there, otherwise I don't believe gluon is used in anything important, so I wouldn't be too worried about public exposure. Either way, thanks for reaching out.
