### ISSUE TITLE
[doc] rust API reference links are broken

### ISSUE THREAD

**Issue by micklat** [gluon-lang/gluon#965]
The link to nightly rust API reference and the stable rust API reference both bring up error messages

broken links:
https://gluon-lang.org/doc/nightly/rust_doc/gluon/index.html
https://gluon-lang.org/doc/crates_io/rust_doc/gluon/index.html

message shown for stable:
```
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<Key>crates_io/rust_doc/gluon/index.html</Key>
<RequestId>JJBT1K1TZ4KMXV2J</RequestId>
<HostId>4PPmXbFENjLrzswZmiAO1wsWTZwJmY87xRjMkyMYIKRyY81iQK21km0DOCNXy2x41H9WovAAFRM=</HostId>
</Error>
```

**Comment by Marwes** [comment]
Strange, I will have a look. The docs are just uploaded to S3 so I have no idea how they are suddentlymissing. You can still use https://docs.rs/gluon/latest/gluon/ though, the docs here are mostly to support. docs on the master branch.
